/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mariane' at '5/8/15 11:03 AM' with Gradle 2.3
 *
 * @author mariane, @date 5/8/15 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
